### ISSUE TITLE
Crear un fichero .gitignore que funcione mejor

### ISSUE THREAD

**Issue by saulroc** [BloodyMary16/calculadora#3]
Os recomiendo utilizar el comando dotnet new gitignore para crear uno que os saque del repositorio las carpetas .vs, bin y obj que os va a generar menos ruido

**Comment by alumnoeficiente** [comment]
De primeras he utilizado el comando dotnet new gitignore, como ya había uno me ha hecho "forzar" la sobreescritura con el comando "dotnet new gitignore --force(o parecido)", al no haber mucho cambio significativo al realizar el commit he borrado 
el archivo "gitignore" y he vuelto a insertar el comando; aparentemente ya se ha insertado el nuevo gitignore de manera satisfactoria.
