### ISSUE TITLE
Cambiar los métodos a public int

### ISSUE THREAD

**Issue by saulroc** [BloodyMary16/calculadora#4]
https://github.com/BloodyMary16/calculadora/blob/f8d2c1482bb3bcebb6338c4e2f09b8a5c6eb2d0b/calculadora.cs#L5

Quitamos de la clase Calculadora los static de sus métodos, y cambiamos void por int para retornar el resultado de las operaciones despues de escribirlas por la consola.

**Comment by alumnoeficiente** [comment]
He cambiado el tipo de variables, métodos, etc; a "decimal" para poder ejecutar correctamente las divisiones, pero se ha cambiado a "public decimal"
